[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.railway"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Service configuration
[environments.production]
serviceName = "weeding-backend"
variables = { 
    APP_ENV = "production", 
    APP_DEBUG = "false",
    APP_NAME = "Wedding Website Backend",
    APP_URL = "https://weeding-backend-production.up.railway.app",
    LOG_CHANNEL = "stack",
    LOG_LEVEL = "error",
    SESSION_DRIVER = "file",
    CACHE_STORE = "file",
    QUEUE_CONNECTION = "sync",
    BCRYPT_ROUNDS = "12"
}