[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.railway"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = { APP_ENV = "production", APP_DEBUG = "false" }